// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApp.DatabaseConnector;

#nullable disable

namespace WeatherApp.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240220140618_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WeatherApp.DatabaseConnector.Entities.WeatherSnapshots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SavedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TemperatureC")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("WeatherSnapshots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Riga",
                            Country = "Latvia",
                            LastUpdate = new DateTime(2024, 2, 20, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            SavedOn = new DateTime(2024, 2, 20, 14, 6, 18, 112, DateTimeKind.Utc).AddTicks(6754),
                            TemperatureC = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            City = "Tallinn",
                            Country = "Estonia",
                            LastUpdate = new DateTime(2024, 2, 20, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            SavedOn = new DateTime(2024, 2, 20, 14, 6, 18, 112, DateTimeKind.Utc).AddTicks(6756),
                            TemperatureC = 1.0m
                        },
                        new
                        {
                            Id = 3,
                            City = "Riga",
                            Country = "Latvia",
                            LastUpdate = new DateTime(2024, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SavedOn = new DateTime(2024, 2, 20, 14, 16, 18, 112, DateTimeKind.Utc).AddTicks(6758),
                            TemperatureC = -0.5m
                        },
                        new
                        {
                            Id = 4,
                            City = "Tallinn",
                            Country = "Estonia",
                            LastUpdate = new DateTime(2024, 2, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            SavedOn = new DateTime(2024, 2, 20, 14, 16, 18, 112, DateTimeKind.Utc).AddTicks(6764),
                            TemperatureC = -1.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
